# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bins <- function(u, v) {
    .Call('_nphawkes_bins', PACKAGE = 'nphawkes', u, v)
}

get_dist_bins <- function(dist_mat, space_breaks) {
    .Call('_nphawkes_get_dist_bins', PACKAGE = 'nphawkes', dist_mat, space_breaks)
}

get_mark <- function(marks, mark_breaks) {
    .Call('_nphawkes_get_mark', PACKAGE = 'nphawkes', marks, mark_breaks)
}

get_time_bins <- function(time_mat, time_breaks) {
    .Call('_nphawkes_get_time_bins', PACKAGE = 'nphawkes', time_mat, time_breaks)
}

get_time <- function(times) {
    .Call('_nphawkes_get_time', PACKAGE = 'nphawkes', times)
}

init_p0 <- function(times) {
    .Call('_nphawkes_init_p0', PACKAGE = 'nphawkes', times)
}

calc_br <- function(p0, times) {
    .Call('_nphawkes_calc_br', PACKAGE = 'nphawkes', p0, times)
}

calc_br_nonstat <- function(p0, times, z, tau) {
    .Call('_nphawkes_calc_br_nonstat', PACKAGE = 'nphawkes', p0, times, z, tau)
}

calc_d <- function(dist_mat2, np) {
    .Call('_nphawkes_calc_d', PACKAGE = 'nphawkes', dist_mat2, np)
}

get_pix <- function(x_grid, y_grid, lat, lon, x_pix, y_pix) {
    .Call('_nphawkes_get_pix', PACKAGE = 'nphawkes', x_grid, y_grid, lat, lon, x_pix, y_pix)
}

calc_tau <- function(x_pix, y_pix, p0, di, lon, lat, times) {
    .Call('_nphawkes_calc_tau', PACKAGE = 'nphawkes', x_pix, y_pix, p0, di, lon, lat, times)
}

calc_z <- function(times, x_pix, y_pix, tau) {
    .Call('_nphawkes_calc_z', PACKAGE = 'nphawkes', times, x_pix, y_pix, tau)
}

get_k <- function(p0, marks, mark_breaks) {
    .Call('_nphawkes_get_k', PACKAGE = 'nphawkes', p0, marks, mark_breaks)
}

get_h <- function(p0, space_breaks, dist_mat) {
    .Call('_nphawkes_get_h', PACKAGE = 'nphawkes', p0, space_breaks, dist_mat)
}

get_g <- function(p0, time_breaks, time_mat) {
    .Call('_nphawkes_get_g', PACKAGE = 'nphawkes', p0, time_breaks, time_mat)
}

update_p <- function(p0, time_mat, dist_mat, mark_mat, g, h, k, space_breaks, time_breaks, mark_breaks, br, time_bins, dist_bins, lat) {
    .Call('_nphawkes_update_p', PACKAGE = 'nphawkes', p0, time_mat, dist_mat, mark_mat, g, h, k, space_breaks, time_breaks, mark_breaks, br, time_bins, dist_bins, lat)
}

check_p <- function(p0, p) {
    .Call('_nphawkes_check_p', PACKAGE = 'nphawkes', p0, p)
}

