# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bins <- function(u, v) {
    .Call('_nphawkes_bins', PACKAGE = 'nphawkes', u, v)
}

get_dist_bins <- function(dist_mat, h_bins) {
    .Call('_nphawkes_get_dist_bins', PACKAGE = 'nphawkes', dist_mat, h_bins)
}

get_mark <- function(marks, k_bins) {
    .Call('_nphawkes_get_mark', PACKAGE = 'nphawkes', marks, k_bins)
}

get_time_bins <- function(time_mat, g_bins) {
    .Call('_nphawkes_get_time_bins', PACKAGE = 'nphawkes', time_mat, g_bins)
}

get_time <- function(times) {
    .Call('_nphawkes_get_time', PACKAGE = 'nphawkes', times)
}

init_p0 <- function(times) {
    .Call('_nphawkes_init_p0', PACKAGE = 'nphawkes', times)
}

calc_br <- function(p0, times) {
    .Call('_nphawkes_calc_br', PACKAGE = 'nphawkes', p0, times)
}

get_k <- function(p0, marks, k_bins) {
    .Call('_nphawkes_get_k', PACKAGE = 'nphawkes', p0, marks, k_bins)
}

get_h <- function(p0, h_bins, dist_mat) {
    .Call('_nphawkes_get_h', PACKAGE = 'nphawkes', p0, h_bins, dist_mat)
}

get_g <- function(p0, g_bins, time_mat) {
    .Call('_nphawkes_get_g', PACKAGE = 'nphawkes', p0, g_bins, time_mat)
}

update_p <- function(p0, time_mat, dist_mat, mark_mat, g, h, k, h_bins, g_bins, k_bins, br, time_bins, dist_bins) {
    .Call('_nphawkes_update_p', PACKAGE = 'nphawkes', p0, time_mat, dist_mat, mark_mat, g, h, k, h_bins, g_bins, k_bins, br, time_bins, dist_bins)
}

check_p <- function(p0, p) {
    .Call('_nphawkes_check_p', PACKAGE = 'nphawkes', p0, p)
}

